// F10-R1: Default_Ignorable_Code_Point, including unassigned code points, must not hide AI attribution.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { evaluateCommit, REQUIRED_EMAIL, REQUIRED_NAME } from '../lib/commit-identity.mjs';
import { CLI_IDENTITY, GOOD_EMAIL, makeRepo, runCli } from './repo.mjs';

const commitLines = (out) => out.split('\n').filter((l) => /^[0-9a-f]{12} /.test(l));

function withRepo(fn) {
  const repo = makeRepo();
  try {
    repo.commitFiles({ 'a.txt': 'base\n' }, 'base');
    return fn(repo, repo.head());
  } finally {
    repo.cleanup();
  }
}

const unassigned = [
  ['U+E0080 (unassigned tag range) inside Codex', 'docs: x\n\nCo-Authored-By: Co\u{E0080}dex <x@example.com>\n'],
  ['U+FFF0 (unassigned) inside Claude, footer', 'docs: x\n\nGenerated with Cl\u{FFF0}aude\n'],
  ['U+2065 (unassigned) in the trailer key', 'docs: x\n\nCo⁥-Authored⁥-By: Codex <x@example.com>\n'],
  ['U+2065 inside the name', 'docs: x\n\nCo-Authored-By: Co⁥dex <x@example.com>\n'],
  ['U+FFF8 and U+E0FFF inside Claude', 'docs: x\n\nCo-Authored-By: Cl\u{FFF8}au\u{E0FFF}de <x@example.com>\n'],
  ['mixed assigned and unassigned ignorables', 'docs: x\n\nCo-Authored-By: C​⁥o\u{E0080}dex <x@example.com>\n'],
];

for (const [label, message] of unassigned) {
  test(`F10-R1: ${label} fails end to end and the message is not echoed`, () =>
    withRepo((repo, base) => {
      repo.commitMessage(message);
      const r = runCli(CLI_IDENTITY, [`${base}..HEAD`], repo.dir);
      assert.equal(r.code, 1, r.out);
      assert.equal(commitLines(r.out).length, 1);
      assert.doesNotMatch(r.out, /odex|laude|example\.com|Generated/i);
    }));
}

test('F10-R1: a committer name with an unassigned ignorable inside Codex fails', () =>
  withRepo((repo, base) => {
    repo.commitMessage('docs: ordinary message\n', { c: { name: 'Co\u{E0080}dex' } });
    const r = runCli(CLI_IDENTITY, [`${base}..HEAD`], repo.dir);
    assert.equal(r.code, 1, r.out);
    assert.match(r.out, /committer name identifies an AI or bot/);
  }));

test('F10-R1: the same characters in ordinary human text create no false AI attribution', () =>
  withRepo((repo, base) => {
    for (const message of [
      'docs: noise\n\nCo-authored-by: Ja\u{E0080}ne Doe <jane@example.com>\n',
      'docs: noise\n\nCo-authored-by: Ja⁥ne D\u{FFF0}oe <jane@example.com>\n',
      'docs: body noise\n\nA sentence with \u{E0080}hidden⁥ characters and Generated by hand.\n',
    ]) {
      repo.commitMessage(message);
      const r = runCli(CLI_IDENTITY, ['HEAD~1..HEAD'], repo.dir);
      assert.equal(r.code, 0, r.out);
    }
    assert.equal(runCli(CLI_IDENTITY, [`${base}..HEAD`], repo.dir).code, 0);
  }));

test('F10-R1: author and committer identity fields stay byte-for-byte exact (never normalized)', () => {
  const ok = {
    hash: 'a'.repeat(40),
    authorName: REQUIRED_NAME,
    authorEmail: REQUIRED_EMAIL,
    committerName: REQUIRED_NAME,
    committerEmail: REQUIRED_EMAIL,
    message: 'docs: x\n',
  };
  assert.equal(evaluateCommit(ok).ok, true);
  for (const bad of [
    { authorName: `${REQUIRED_NAME}​` },
    { authorName: `${REQUIRED_NAME}\u{E0080}` },
    { authorEmail: `${REQUIRED_EMAIL}⁥` },
    { committerEmail: `\u{E0080}${REQUIRED_EMAIL}` },
    { committerEmail: REQUIRED_EMAIL.toUpperCase() },
  ]) {
    assert.equal(evaluateCommit({ ...ok, ...bad }).ok, false, JSON.stringify(bad));
  }
});

test('F10-R1: the same identity exactness holds end to end', () =>
  withRepo((repo, base) => {
    repo.commitMessage('docs: x\n', { a: { name: 'oAziz94⁥' } });
    assert.equal(runCli(CLI_IDENTITY, [`${base}..HEAD`], repo.dir).code, 1);
    repo.commitMessage('docs: x\n', { c: { email: `${GOOD_EMAIL}\u{E0080}` } });
    assert.equal(runCli(CLI_IDENTITY, ['HEAD~1..HEAD'], repo.dir).code, 1);
  }));
